### ISSUE TITLE
p2p code review - all comments are welcome!

### ISSUE THREAD

**Issue by dili021** [dili021/Apple-clone#2]

**Comment by nyatindopatrick** [comment]
Impressive though i thought you should have a look at this:
- There's quite a big space between the hero and the bottom images. You can try fixing this by setting height for the hero image by setting it to cover the grid template row height.

Good work though.
![Screen Shot 2020-01-30 at 10 13 53](https://user-images.githubusercontent.com/48393059/73428214-ab125380-4349-11ea-949e-efc3a9ccb19c.png)

**Comment by patriciachrysy** [comment]
Good job Stefan, especially on the navbar gradient!!! Your code is very clean as you said too. I just have some few remarks:
- The text in the top section should be centered
- The search icon should be inside the input. You can use a negative right margin to push it inside
- the footer  is too large, maybe if you reduce the padding/margin of your li tags it will be better

**Comment by Kyle-Law** [comment]
Good job @dili021 ! I love how delicate and exquisite your navbar is by giving them 5-colors linear gradient and slight box-shadow. 

It'd be perfect if you could add `text-decoration: underline;` to `footer a:hover{}` for the underline effect on hover. 

Nonetheless, it's a detailed clone!
